//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angajati()
        {
            this.Planficares = new HashSet<Planficare>();
            this.Pontajs = new HashSet<Pontaj>();
        }
    
        public System.Guid ID_Angajat { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public int ID_Functie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planficare> Planficares { get; set; }
        public virtual Functii Functii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pontaj> Pontajs { get; set; }
        public override string ToString()
        {
            return Nume + " " + Prenume;
        }
    }
   
}
