//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Functii()
        {
            this.Angajatis = new HashSet<Angajati>();
            this.SchimburiFuncties = new HashSet<SchimburiFunctie>();
        }
    
        public int ID_Functie { get; set; }
        public string Denumire { get; set; }
        public decimal Salariu_per_Ora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Angajati> Angajatis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchimburiFunctie> SchimburiFuncties { get; set; }
    }
}
