//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pontaj
    {
        public int ID_Pontaj { get; set; }
        public Nullable<System.Guid> ID_Angajat { get; set; }
        public string Clock_In { get; set; }
        public string Clock_Out { get; set; }
    
        public virtual Angajati Angajati { get; set; }
    }
}
