//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchimburiFunctie
    {
        public int ID { get; set; }
        public Nullable<int> ID_Functie { get; set; }
        public Nullable<int> ID_Schimb { get; set; }
    
        public virtual Functii Functii { get; set; }
        public virtual Schimburi Schimburi { get; set; }
    }
}
